export const reports = [
  {
    id: 1,
    first_name: "Alex",
    last_name: "Johnson",
    expected_hours: 40,
    actual_hours_work: 38,
    total_hours_work: 38,
    end_date: "2024-10-15",
    utilization: "95%",
    consultant_client: "Project Alpha",
    activity_type: "Development",
    status: "pending",
  },
  {
    id: 2,
    first_name: "Sarah",
    last_name: "Lee",
    expected_hours: 40,
    actual_hours_work: 40,
    total_hours_work: 40,
    end_date: "2024-10-15",
    utilization: "100%",
    consultant_client: "Project Alpha",
    activity_type: "Testing",
    status: "pending",
  },
  {
    id: 3,
    first_name: "Michael",
    last_name: "Green",
    expected_hours: 40,
    actual_hours_work: 42,
    total_hours_work: 42,
    end_date: "2024-10-15",
    utilization: "106%",
    consultant_client: "Project Alpha",
    activity_type: "Design",
    status: "pending",
  },
  {
    id: 4,
    first_name: "Emma",
    last_name: "Taylor",
    expected_hours: 40,
    actual_hours_work: 40,
    total_hours_work: 40,
    end_date: "2024-10-15",
    utilization: "100%",
    consultant_client: "Project Alpha",
    activity_type: "Meeting",
    status: "pending",
  },
];

export default reports;
