export const dummyConsultants = [
  {
    id: 1,
    first_name: "Alex",
    last_name: "Johnson",
    email: "alex.johnson@email.com",
    sex: "Male",
    title: "Senior Consultant",
    compensation_type: "Hourly",
    weekly_hours_expectation: 40,
    actual_utilization: null,
    bill_rate: 150,
  },
  {
    id: 2,
    first_name: "Sarah",
    last_name: "Lee",
    email: "sarah.lee@email.com",
    sex: "Female",
    title: "Project Manager",
    compensation_type: "Salary",
    weekly_hours_expectation: 40,
    actual_utilization: null,
    bill_rate: 8000,
  },
  {
    id: 3,
    first_name: "Michael",
    last_name: "Green",
    email: "michael.green@email.com",
    sex: "Male",
    title: "Business Analyst",
    compensation_type: "Hourly",
    weekly_hours_expectation: 40,
    actual_utilization: null,
    bill_rate: 95,
  },
  {
    id: 4,
    first_name: "Emma",
    last_name: "Taylor",
    email: "emma.taylor@email.com",
    sex: "Female",
    title: "IT Consultant",
    compensation_type: "Hourly",
    weekly_hours_expectation: 40,
    actual_utilization: null,
    bill_rate: 110,
  },
];

export default dummyConsultants;
